/* The product mark: the certificate seal's guilloché rosette (see Rosette.tsx), reduced to
   one ring and one six-lobed rosette so it still reads at the 16px a browser tab gives it.
   The certificate draws five concentric twelve-lobed curves at ~120px; shrunk, that is mud.

   Paths are built once at module scope, as Rosette does, rather than per render.

   frontend/public/favicon.svg is the same figure as a static file, generated by
   scripts/generate-mark.mjs. It is duplicated rather than shared because that is a Node
   script and this is a component; if the geometry changes here it must change there too.

   Stroke is currentColor, so the mark takes the surface's colour — navy on paper, cream on
   the desk — from CSS and not from here. */
const CENTRE = 16;
const RING_RADIUS = 14.6;

const ROSETTE_PATH: string = (() => {
  const radius = 9.8;
  const amplitude = 1.9;
  const lobes = 6;
  const samples = 360;
  let d = "";

  for (let i = 0; i <= samples; i += 1) {
    const t = (i / samples) * Math.PI * 2;
    const r = radius + amplitude * Math.cos(lobes * t);
    d += `${i ? "L" : "M"}${(CENTRE + r * Math.cos(t)).toFixed(2)} ${(CENTRE + r * Math.sin(t)).toFixed(2)}`;
  }

  return `${d}Z`;
})();

export function Mark({ size = 22 }: { size?: number }) {
  return (
    /* aria-hidden: it sits beside the wordmark, which already names the product, so
       announcing it would read the name twice. */
    <svg className="mark" width={size} height={size} viewBox="0 0 32 32" aria-hidden="true" focusable="false">
      <g fill="none" stroke="currentColor" strokeLinejoin="round">
        <circle cx={CENTRE} cy={CENTRE} r={RING_RADIUS} strokeWidth={1.35} />
        <path d={ROSETTE_PATH} strokeWidth={1.8} />
      </g>
    </svg>
  );
}
