import { type FormEvent, useMemo, useState } from "react";
import { chainAdapter, type DemoGrant, type GrantState } from "./chainAdapter";

const routes = ["/", "/employer/fund", "/employer/grants", "/contractor/grant"] as const;
type Route = (typeof routes)[number];
const initialGrant: DemoGrant = { id: "GRANT-0000", contractor: "Configure a test grant", stock: "AAPL", stockAmount: "—", usdgAmount: "—", milestone: "Ship the Robinhood Chain testnet integration", deadline: "15 October 2026", state: "LOCKED" };

function useRoute(): [Route, (route: Route) => void] {
  const initial = routes.includes(window.location.pathname as Route) ? window.location.pathname as Route : "/";
  const [route, setRoute] = useState<Route>(initial);
  return [route, (next) => { window.history.pushState({}, "", next); setRoute(next); }];
}

function Header({ navigate }: { navigate: (route: Route) => void }) {
  const [wallet, setWallet] = useState<string>(); const [error, setError] = useState<string>();
  const connect = async () => { try { setWallet(await chainAdapter.connectWallet()); setError(undefined); } catch (reason) { setError(reason instanceof Error ? reason.message : "Wallet connection failed."); } };
  return <><header className="site-header"><button className="wordmark" onClick={() => navigate("/")}>Equity Benefit Wallet</button><nav aria-label="Primary navigation"><button onClick={() => navigate("/employer/fund")}>For employers</button><button onClick={() => navigate("/contractor/grant")}>For contractors</button></nav><button className="wallet-button" onClick={connect}>{wallet ? `${wallet.slice(0, 6)}…${wallet.slice(-4)}` : "Connect wallet"}</button></header>{error && <p className="wallet-error" role="alert">{error}</p>}</>;
}

function Badge({ state }: { state: GrantState }) { const label = state === "LOCKED" ? "Locked" : state === "UNLOCKED" ? "Unlocked" : "Claimed"; return <span className={`seal seal-${state.toLowerCase()}`}>{label}</span>; }
function Certificate({ grant }: { grant: DemoGrant }) { const label = grant.state === "LOCKED" ? "Locked — held" : grant.state === "UNLOCKED" ? "Unlocked" : "Claimed"; return <article className="cert"><div className="cert-inner"><div className="cert-core"><div className="cert-top"><p className="eyebrow">Equity benefit grant</p><Badge state={grant.state} /></div><div className="cert-value"><span>{grant.stock}</span><strong>{grant.stockAmount}</strong><small>test stock tokens</small></div><div className="rule" /><dl className="certificate-details"><div><dt>Milestone</dt><dd>{grant.milestone}</dd></div><div><dt>Deadline</dt><dd>{grant.deadline}</dd></div><div><dt>Grant status</dt><dd>{label}</dd></div></dl><footer className="certificate-foot"><span>{grant.id}</span><span>Testnet certificate</span></footer></div></div></article>; }

function Notice() { return <p className="testnet-notice">Robinhood Chain Testnet demo. Assets shown here are test contracts, not real securities.</p>; }
function Landing({ navigate }: { navigate: (route: Route) => void }) { return <main className="landing"><Notice /><section className="hero"><div className="hero-copy"><p className="eyebrow">For thoughtful contractor rewards</p><h1>Give a bonus that stays meaningful.</h1><p className="lede">Equity Benefit Wallet lets employers hold a stock-token bonus in a simple onchain grant until a contractor earns it.</p><div className="actions"><button className="button button-primary" onClick={() => navigate("/employer/fund")}>Give a bonus</button><button className="button button-secondary" onClick={() => navigate("/contractor/grant")}>Claim your bonus</button></div><p className="trust-copy">The contract holds your selected stock until the milestone is confirmed. If it is not released by the deadline, <strong>claim it yourself</strong>.</p></div><Certificate grant={initialGrant} /></section><section className="how-it-works"><p className="eyebrow">A clear agreement, not a black box</p><h2>How it works</h2><ol><li><span>01</span><div><h3>Choose the bonus</h3><p>Select a test stock and set the USDG funding amount.</p></div></li><li><span>02</span><div><h3>Fund the grant</h3><p>The test contract holds the selected mock stock and records the deadline.</p></div></li><li><span>03</span><div><h3>Release or claim</h3><p>Release now when the milestone is met, or claim it yourself after the deadline.</p></div></li></ol></section></main>; }

function EmployerFund({ navigate }: { navigate: (route: Route) => void }) {
  const [stock, setStock] = useState<DemoGrant["stock"]>("AAPL"); const [message, setMessage] = useState<string>(); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { setBusy(true); const id = await chainAdapter.fundGrant({ contractor: form.get("contractor") as `0x${string}`, deadline: new Date(form.get("deadline") as string), stock, usdgAmount: form.get("usdg") as string }); setMessage(`Grant ${id.toString()} was funded on testnet. Open contractor view and load this grant ID.`); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Funding failed."); } finally { setBusy(false); } };
  return <main className="page-shell"><Notice /><section className="page-heading"><p className="eyebrow">Employer workspace · testnet</p><h1>Fund a benefit grant</h1><p>Review every detail before signing the testnet transactions.</p></section><div className="form-layout"><form className="paper-form" onSubmit={submit}><label>Contractor address<input required name="contractor" placeholder="0x…" pattern="0x[a-fA-F0-9]{40}" /></label><label>Milestone<input name="milestone" required defaultValue={initialGrant.milestone} /></label><div className="form-row"><label>Deadline<input required name="deadline" type="date" /></label><label>Selected stock<select value={stock} onChange={(event) => setStock(event.target.value as DemoGrant["stock"])}><option>AAPL</option><option>TSLA</option><option>NVDA</option></select></label></div><label>USDG funding amount<input required name="usdg" type="number" min="1" step="0.000001" defaultValue="100" /></label><button className="button button-primary" disabled={busy} type="submit">{busy ? "Funding…" : "Review and fund"}</button>{message && <p className="form-notice" role="status">{message}</p>}</form><aside className="review-slip"><p className="eyebrow">Grant summary</p><h2>{stock} test bonus</h2><p>The contract will approve USDG, create the Grant, swap through the deterministic mock adapter, and hold test stock until release or timeout claim.</p></aside></div></main>;
}

function EmployerGrants({ navigate }: { navigate: (route: Route) => void }) { return <main className="page-shell"><Notice /><section className="page-heading inline-heading"><div><p className="eyebrow">Employer workspace · testnet</p><h1>Your grants</h1></div><button className="button button-primary" onClick={() => navigate("/employer/fund")}>Give a bonus</button></section><section className="ledger-note"><p className="eyebrow">Read a deployed grant</p><p>Use the contractor view to load a Grant ID directly from the configured test contract.</p></section></main>; }

function ContractorGrant() {
  const [grantId, setGrantId] = useState("0"); const [grant, setGrant] = useState<DemoGrant>(initialGrant); const [message, setMessage] = useState<string>(); const [busy, setBusy] = useState(false);
  const id = () => BigInt(grantId);
  const load = async () => { try { setBusy(true); setGrant(await chainAdapter.getGrant(id())); setMessage("Grant loaded from the configured Robinhood testnet contract."); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Could not read grant."); } finally { setBusy(false); } };
  const act = async (action: "release" | "claim") => { try { setBusy(true); if (action === "release") await chainAdapter.releaseGrant(id()); else await chainAdapter.claimAfterTimeout(id()); await load(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Transaction failed."); } finally { setBusy(false); } };
  const state = useMemo(() => grant.state, [grant]);
  return <main className="contractor-page"><Notice /><section className="contractor-intro"><p className="eyebrow">Contractor view · testnet</p><h1>Your equity bonus</h1><p>This Grant is held by the test contract. Load a Grant ID to read its current onchain status.</p><div className="grant-loader"><input aria-label="Grant ID" value={grantId} onChange={(event) => setGrantId(event.target.value)} inputMode="numeric" /><button className="button button-secondary" onClick={load} disabled={busy}>Load grant</button></div></section><Certificate grant={grant} /><section className="claim-panel"><div><p className="eyebrow">Milestone and deadline</p><h2>{state === "LOCKED" ? "Your grant is Locked" : state === "UNLOCKED" ? "Your bonus is Unlocked" : "Your bonus is Claimed"}</h2><p>{message ?? "Release now before the deadline, or claim it yourself only at or after the deadline."}</p></div><div className="claim-actions">{state === "LOCKED" && <><button className="button button-primary" onClick={() => act("release")} disabled={busy}>Release now</button><button className="button button-claim" onClick={() => act("claim")} disabled={busy}>Claim it yourself</button></>}{state === "CLAIMED" && <span className="claimed-copy">Certificate complete</span>}</div></section></main>;
}

export function App() { const [route, navigate] = useRoute(); return <><Header navigate={navigate} />{route === "/" && <Landing navigate={navigate} />}{route === "/employer/fund" && <EmployerFund navigate={navigate} />}{route === "/employer/grants" && <EmployerGrants navigate={navigate} />}{route === "/contractor/grant" && <ContractorGrant />}<footer className="site-footer"><span>Equity Benefit Wallet</span><span>Robinhood Chain Testnet · mock contracts only</span></footer></>; }
