import { type FormEvent, useMemo, useState } from "react";
import { chainAdapter, type DemoGrant, type GrantState } from "./chainAdapter";

const routes = ["/", "/employer/fund", "/employer/grants", "/contractor/grant"] as const;
type Route = (typeof routes)[number];
const initialGrant: DemoGrant = { id: "GRANT-0000", contractor: "Configure a test grant", stock: "AAPL", stockAmount: "—", usdgAmount: "—", milestone: "Ship the Robinhood Chain testnet integration", deadline: "15 October 2026", state: "LOCKED" };

function useRoute(): [Route, (route: Route) => void] {
  const initial = routes.includes(window.location.pathname as Route) ? window.location.pathname as Route : "/";
  const [route, setRoute] = useState<Route>(initial);
  return [route, (next) => { window.history.pushState({}, "", next); setRoute(next); }];
}

function Header({ navigate }: { navigate: (route: Route) => void }) {
  const [wallet, setWallet] = useState<string>();
  const [error, setError] = useState<string>();
  const connect = async () => { try { setWallet(await chainAdapter.connectWallet()); setError(undefined); } catch (reason) { setError(reason instanceof Error ? reason.message : "Wallet connection failed."); } };
  return <><header className="site-header"><button className="wordmark" onClick={() => navigate("/")}>Equity Benefit Wallet</button><nav aria-label="Primary navigation"><button onClick={() => navigate("/employer/fund")}>Give a bonus</button><button onClick={() => navigate("/contractor/grant")}>Claim a grant</button></nav><button className="wallet-button" onClick={connect}>{wallet ? `${wallet.slice(0, 6)}…${wallet.slice(-4)}` : "Connect wallet"}</button></header>{error && <p className="wallet-error" role="alert">{error}</p>}</>;
}

function Badge({ state }: { state: GrantState }) { const label = state === "LOCKED" ? "Locked" : state === "UNLOCKED" ? "Unlocked" : "Claimed"; return <span className={`seal seal-${state.toLowerCase()}`}>{label}</span>; }
function Certificate({ grant }: { grant: DemoGrant }) {
  const status = grant.state === "LOCKED" ? "Locked · held" : grant.state === "UNLOCKED" ? "Unlocked" : "Claimed";
  return <article className="cert" aria-label={`${grant.stock} equity benefit grant`}><div className="cert-inner"><div className="cert-core"><div className="cert-top"><div><p className="eyebrow">Equity benefit grant</p><p className="cert-reference">Contract-held testnet certificate</p></div><Badge state={grant.state} /></div><div className="cert-value"><span>{grant.stock}</span><strong>{grant.stockAmount}</strong><small>test stock tokens</small></div><div className="rule" /><dl className="certificate-details"><div><dt>Milestone</dt><dd>{grant.milestone}</dd></div><div className="certificate-pair"><div><dt>Deadline</dt><dd>{grant.deadline}</dd></div><div><dt>Status</dt><dd>{status}</dd></div></div></dl><footer className="certificate-foot"><span>{grant.id}</span><span>Robinhood Chain Testnet</span></footer></div></div></article>;
}

function Notice() { return <p className="testnet-notice">Robinhood Chain Testnet demo. Assets shown here are test contracts, not real securities.</p>; }

function Landing({ navigate }: { navigate: (route: Route) => void }) {
  return <main className="landing"><Notice /><section className="hero"><div className="hero-copy"><p className="eyebrow">For thoughtful contractor rewards</p><h1>Give a bonus that stays meaningful.</h1><p className="lede">Give a contractor a stock-based bonus held by a contract until the milestone is met or the agreed deadline arrives.</p><div className="actions"><button className="button button-primary" onClick={() => navigate("/employer/fund")}>Give a bonus</button><button className="button button-secondary" onClick={() => navigate("/contractor/grant")}>Claim your bonus</button></div><aside className="trust-copy"><strong>No trust required.</strong><p>Your bonus isn't held by a company or an app. A contract holds it. If your employer goes quiet, you can claim it yourself, automatically, on the date shown above — no lawyer, no waiting on goodwill.</p></aside></div><Certificate grant={initialGrant} /></section><section className="how-it-works"><p className="eyebrow">A clear agreement, not a black box</p><h2>How the Grant works</h2><ol><li><span>01</span><div><h3>Choose the bonus</h3><p>An employer selects a stock-based bonus and records the milestone.</p></div></li><li><span>02</span><div><h3>The contract holds it</h3><p>The Grant holds the selected test stock until the agreed deadline.</p></div></li><li><span>03</span><div><h3>Release or claim</h3><p>Release now when work is complete. Otherwise, claim it yourself after the deadline.</p></div></li></ol></section></main>;
}

function EmployerFund() {
  const [stock, setStock] = useState<DemoGrant["stock"]>("AAPL"); const [message, setMessage] = useState<string>(); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { setBusy(true); const id = await chainAdapter.fundGrant({ contractor: form.get("contractor") as `0x${string}`, deadline: new Date(form.get("deadline") as string), stock, usdgAmount: form.get("usdg") as string }); setMessage(`Grant ${id.toString()} was funded on testnet. Open the contractor view and load this Grant ID.`); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Funding failed."); } finally { setBusy(false); } };
  return <main className="page-shell"><Notice /><section className="page-heading"><p className="eyebrow">Employer workspace · testnet</p><h1>Set up a benefit Grant</h1><p>Turn a clear agreement into a contract-held bonus. You will review and sign each testnet transaction.</p></section><div className="fund-layout"><form className="paper-form" onSubmit={submit}><fieldset><legend>Who is this for?</legend><label>Contractor address<input required name="contractor" placeholder="0x…" pattern="0x[a-fA-F0-9]{40}" /></label></fieldset><fieldset><legend>What did you agree?</legend><label>Milestone<input name="milestone" required defaultValue={initialGrant.milestone} /></label><label>Deadline<input required name="deadline" type="date" /></label></fieldset><fieldset><legend>What is the bonus?</legend><div className="form-row"><label>Test stock<select value={stock} onChange={(event) => setStock(event.target.value as DemoGrant["stock"])}><option>AAPL</option><option>TSLA</option><option>NVDA</option></select></label><label>USDG amount<input required name="usdg" type="number" min="1" step="0.000001" defaultValue="100" /></label></div></fieldset><button className="button button-primary" disabled={busy} type="submit">{busy ? "Funding…" : "Review and fund"}</button>{message && <p className="form-notice" role="status">{message}</p>}</form><aside className="review-slip"><p className="eyebrow">Before you sign</p><h2>{stock} test bonus</h2><dl><div><dt>1. Create</dt><dd>Set the contractor and deadline.</dd></div><div><dt>2. Fund</dt><dd>Approve USDG and fund the Grant.</dd></div><div><dt>3. Hold</dt><dd>The contract holds the test stock until release or timeout claim.</dd></div></dl><p className="review-note">The demo uses a deterministic mock adapter. Assets are test contracts, not real securities.</p></aside></div></main>;
}

function EmployerGrants({ navigate }: { navigate: (route: Route) => void }) { return <main className="page-shell"><Notice /><section className="page-heading inline-heading"><div><p className="eyebrow">Employer workspace · testnet</p><h1>Your Grants</h1><p>Read a deployed Grant directly from the contractor view.</p></div><button className="button button-primary" onClick={() => navigate("/employer/fund")}>Give a bonus</button></section><section className="ledger-note"><p className="eyebrow">Grant ledger</p><p>This testnet MVP reads Grants by ID. Share the funded Grant ID with the contractor so they can review the certificate and claim path.</p></section></main>; }

function ContractorGrant() {
  const [grantId, setGrantId] = useState("0"); const [grant, setGrant] = useState<DemoGrant>(initialGrant); const [message, setMessage] = useState<string>(); const [busy, setBusy] = useState(false);
  const id = () => BigInt(grantId);
  const load = async () => { try { setBusy(true); setGrant(await chainAdapter.getGrant(id())); setMessage("Grant loaded from the configured Robinhood testnet contract."); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Could not read Grant."); } finally { setBusy(false); } };
  const act = async (action: "release" | "claim") => { try { setBusy(true); if (action === "release") await chainAdapter.releaseGrant(id()); else await chainAdapter.claimAfterTimeout(id()); await load(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Transaction failed."); } finally { setBusy(false); } };
  const state = useMemo(() => grant.state, [grant]);
  const actionTitle = state === "CLAIMED" ? "This Grant is complete" : state === "UNLOCKED" ? "Your bonus is unlocked" : "Your Grant is locked and held";
  return <main className="contractor-page"><Notice /><section className="contractor-intro"><p className="eyebrow">Contractor view · testnet</p><h1>Your equity bonus</h1><p>Load a Grant ID to see the contract-held stock bonus, its milestone, and its deadline.</p><div className="grant-loader"><input aria-label="Grant ID" value={grantId} onChange={(event) => setGrantId(event.target.value)} inputMode="numeric" /><button className="button button-secondary" onClick={load} disabled={busy}>Load Grant</button></div></section><Certificate grant={grant} /><section className="claim-panel"><div><p className="eyebrow">Your next step</p><h2>{actionTitle}</h2><p>{message ?? (state === "CLAIMED" ? "The certificate has been paid to the contractor." : "The employer can release now before the deadline. If they do not, you can claim it yourself on or after the deadline.")}</p></div><div className="claim-actions">{state === "LOCKED" && <><button className="button button-primary" onClick={() => act("release")} disabled={busy}>Release now</button><button className="text-action" onClick={() => act("claim")} disabled={busy}>Claim it yourself after deadline</button></>}{state === "UNLOCKED" && <button className="button button-primary" onClick={() => act("release")} disabled={busy}>Release now</button>}{state === "CLAIMED" && <span className="claimed-copy">Certificate complete</span>}</div></section></main>;
}

export function App() { const [route, navigate] = useRoute(); return <><Header navigate={navigate} />{route === "/" && <Landing navigate={navigate} />}{route === "/employer/fund" && <EmployerFund />}{route === "/employer/grants" && <EmployerGrants navigate={navigate} />}{route === "/contractor/grant" && <ContractorGrant />}<footer className="site-footer"><span>Equity Benefit Wallet</span><span>Robinhood Chain Testnet · mock contracts only</span></footer></>; }
